#!/bin/sh

NAME=collector
IMG=$NAME
IMG_VERSION=latest
CONTAINER=$IMG
HOST=$NAME
DOCKER_HUB_IMG=caquicode/$NAME
KAFKA_CONTAINER=kafka
KAFKA_HOST=kafka
ZK_CONTAINER=zookeeper
ZK_HOST=zookeeper
INFLUXDB_CONTAINER=influxdb
INFLUXDB_HOST=influxdb
DEBUG_PORT=6006

docker stop $CONTAINER
docker rm $CONTAINER

docker run -d -h $HOST --name $CONTAINER --link $KAFKA_CONTAINER:$KAFKA_HOST \
	--link $INFLUXDB_CONTAINER:$INFLUXDB_HOST \
	--link $ZK_CONTAINER:$ZK_HOST --env DEBUG_PORT=$DEBUG_PORT \
	-p $DEBUG_PORT:$DEBUG_PORT $DOCKER_HUB_IMG:$IMG_VERSION
# docker logs -f $CONTAINER
