#!/bin/sh

NAME=src-percent
IMG=$NAME
IMG_VERSION=latest
CONTAINER=$IMG
HOST=$NAME
DOCKER_HUB_IMG=caquicode/$NAME
KAFKA_CONTAINER=kafka
KAFKA_HOST=kafka
ZK_CONTAINER=zookeeper
ZK_HOST=zookeeper
DELAY_IN_MILLIS=5000
MEASUREMENT=percent
DEBUG_PORT=6006

docker stop $CONTAINER
docker rm $CONTAINER

docker run -d -h $HOST --name $CONTAINER --link $KAFKA_CONTAINER:$KAFKA_HOST \
	--link $ZK_CONTAINER:$ZK_HOST --env DEBUG_PORT=$DEBUG_PORT \
	--env DELAY_IN_MILLIS=$DELAY_IN_MILLIS --env MEASUREMENT=$MEASUREMENT \
	-p $DEBUG_PORT:$DEBUG_PORT $DOCKER_HUB_IMG:$IMG_VERSION
# docker logs -f $CONTAINER
